// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldewzndhrfhvxbjtkevv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkZXd6bmRocmZodnhianRrZXZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjI3MTYsImV4cCI6MjA2NTg5ODcxNn0.Qxfb_onHVpSrR3OyUKiYGBGr8SCDqC593XsK-Y9JuUI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});